# Generated by Django 4.0.2 on 2022-02-17 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='catergory',
        ),
    ]
