# Generated by Django 4.0.2 on 2022-02-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menuitem_catergory'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(default='main', max_length=255),
            preserve_default=False,
        ),
    ]
